 baseURL = "https://mgelvoleo.github.io/blog/"
# baseURL = "/"
languageCode = 'en-us'
title = 'ITLEARNTV'
theme = "mainroad"
publishDir = "public"

canonifyURLs = true  # Ensures absolute URLs
# relativeURLs = true  # REMOVE THIS

[Params]
  post_meta = ["author", "date", "categories", "translations"]
  copyright = "© 2025 Your Custom Text"

[Params.logo]
  image = "img/placeholder.png"
  title = "Mainroad"
  subtitle = "Just another site"

[Params.sidebar]
  home = "right"
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "Linux"
    url = "/linux"
    weight = 2
  [[menu.main]]
    name = "Ansible"
    url = "/ansible"
    weight = 3

  [[menu.main]]
    name = "Terraform"
    url = "/terraform"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 5

[Params.widgets]
  recent_num = 5
  tags_counter = true

[Params.widgets.social]
  cached = false
  twitter = "username"
  linkedin = "username"
  github = "username"

[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/user/username"
  rel = "noopener noreferrer"


  

